{
 "title": "Status",
 "tags": [
  "automation",
  "apps",
  "solana",
  "validators_monitoring",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "container", "query": "solana-validators-monitoring" },
   { "name": "service", "query": "solana-validators-monitoring" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(solana_validators_monitoring_build_info, env)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(solana_validators_monitoring_build_info{env=~\"$env\"}, source)"
    }
   },
   { "name": "search", "label": "Search query" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(solana_validators_monitoring_nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_build_info"
      }
     ]
    },
    {
     "title": "Branch",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_build_info"
      }
     ]
    },
    {
     "title": "Commit",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_build_info"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Container uptime",
   "type": "stat",
   "description": "Bot container uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"$container\",env=~\"$env\",source=~\"$source\"}"
    }
   ]
  },
  {
   "title": "Solana RPC requests fails count",
   "type": "stat",
   "description": "Count of fails outgoing PRC requests",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(solana_validators_monitoring_outgoing_rpc_requests_count{env=~\"$env\",source=~\"$source\",status=\"error\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tasks fails count",
   "type": "stat",
   "description": "Count of fails inside the app modules",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(solana_validators_monitoring_task_result_count{env=~\"$env\",source=~\"$source\",status=\"error\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Solana RPC requests count",
   "type": "stat",
   "description": "Count of outgoing PRC requests",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_outgoing_rpc_requests_count{env=~\"$env\",source=~\"$source\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Tasks result count",
   "type": "stat",
   "description": "Count of internal app tasks result",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_task_result_count{env=~\"$env\",source=~\"$source\"}[$__range]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Solana RPC requests duration",
   "type": "heatmap",
   "description": "Duration of requests to Solana RPC",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_outgoing_rpc_requests_duration_seconds_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Solana RPC requests errors",
   "type": "timeseries",
   "description": "Number of request errors to Solana RPC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_outgoing_rpc_requests_count{env=~\"$env\",source=~\"$source\",status=\"error\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Tasks duration",
   "type": "heatmap",
   "description": "Duration of tasks",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_task_duration_seconds_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Tasks errors",
   "type": "timeseries",
   "description": "Number of task errors",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(solana_validators_monitoring_task_result_count{env=~\"$env\",source=~\"$source\",status=\"error\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json | line_format \"[{{.level}}] {{.message}}\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "{container_name=\"$container\",env=~\"$env\",source=~\"$source\"} | json |= \"error\" | line_format \"[{{.level}}] {{.message}}\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(irate(container_cpu_user_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100) + (sum(irate(container_cpu_system_seconds_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name) *100)",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{env=~\"$env\",source=~\"$source\",name=~\"$container\"}) by (name)",
       "legendFormat": "mem"
      }
     ]
    },
    {
     "title": "Opened FDs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{env=~\"$env\",source=~\"$source\",name=~\"$container\"}",
       "legendFormat": "FDs"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name)) + (sum(irate(container_network_transmit_bytes_total{env=~\"$env\",source=~\"$source\",name=~\"$container\"}[5m])) by (name))",
       "legendFormat": "net"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(solana_validators_monitoring_process_cpu_user_seconds_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "User CPU - {{instance}}"
      },
      {
       "expr": "irate(solana_validators_monitoring_process_cpu_system_seconds_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[2m]) * 100",
       "legendFormat": "Sys CPU - {{instance}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 10, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_nodejs_eventloop_lag_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node.js Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(solana_validators_monitoring_nodejs_version_info{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Process Restart Times",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(solana_validators_monitoring_process_start_time_seconds{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_process_resident_memory_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Process Memory - {{instance}}"
      },
      {
       "expr": "solana_validators_monitoring_nodejs_heap_size_total_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}}"
      },
      {
       "expr": "solana_validators_monitoring_nodejs_heap_size_used_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}}"
      },
      {
       "expr": "solana_validators_monitoring_nodejs_external_memory_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_nodejs_active_handles_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Active Handler - {{instance}}"
      },
      {
       "expr": "solana_validators_monitoring_nodejs_active_requests_total{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Active Request - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Total Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_nodejs_heap_space_size_total_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Heap Total - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Used Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "solana_validators_monitoring_nodejs_heap_space_size_used_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Available Detail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "solana_validators_monitoring_nodejs_heap_space_size_available_bytes{env=~\"$env\",source=~\"$source\",instance=~\"$instance\"}",
       "legendFormat": "Heap Used - {{instance}} - {{space}}"
      }
     ]
    },
    {
     "title": "Garbage collection duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(solana_validators_monitoring_nodejs_gc_duration_seconds_bucket{env=~\"$env\",source=~\"$source\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}