{
 "title": "Solana Validators",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "last_fetch_timestamp",
    "label": "Last fetch timestamp",
    "query": {
     "query": "query_result(solana_validators_monitoring_last_fetch_timestamp)"
    }
   },
   {
    "name": "current_epoch",
    "label": "Current epoch",
    "query": {
     "query": "query_result(solana_validators_monitoring_current_epoch)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validators_monitoring_current_epoch"
    }
   ]
  },
  {
   "title": "All active validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(solana_validators_monitoring_cluster_validators_count{status=~\"offline|online\"})"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_validators_count{status=\"online\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_validators_count{status=\"offline\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Out of epoch validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_validators_count{status=\"out_of_epoch\"}",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Data actuality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - solana_validators_monitoring_last_fetch_timestamp / 1000"
    }
   ]
  },
  { "title": "Operators Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Update list in 24 hours",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"fetchTimestamp\" as \"Updated at\",\n  operator as \"Operator\",\n  \"prevVersion\" as \"Previous\", \n  version as \"New\",\n  \"updateTime\" as \"Update time\"\nFROM\n  validator\nWHERE operator != 'unknown' AND (\"prevVersion\" != version OR \"prevVersion\" is NULL AND version is NOT NULL) AND \"fetchTimestamp\" >= (${last_fetch_timestamp} - 86400000)::bigint\nORDER BY \"fetchTimestamp\" DESC, operator"
    }
   ]
  },
  {
   "title": "User validators info",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  operator,\n  version,\n  status\nFROM\n  validator\nWHERE operator != 'unknown' AND \"fetchTimestamp\" = ${last_fetch_timestamp}::bigint\nORDER BY status, version DESC"
    }
   ]
  },
  {
   "title": "Uptime percentage (24h)",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort((86400 - increase(solana_validators_monitoring_down_time[1d])) / 86400 * 100)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  { "title": "Operators Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Average cluster skip rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_avg_skip_rate"
    }
   ]
  },
  {
   "title": "Operators skip rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 34 },
   "targets": [
    {
     "expr": "solana_validators_monitoring_skip_rate",
     "legendFormat": "{{ operator }} "
    }
   ]
  },
  {
   "title": "Average User skip rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(solana_validators_monitoring_skip_rate)"
    }
   ]
  },
  {
   "title": "Average cluster down time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_avg_down_time"
    }
   ]
  },
  {
   "title": "Operators down time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 46 },
   "targets": [
    {
     "expr": "solana_validators_monitoring_down_time",
     "legendFormat": "{{ operator }} "
    }
   ]
  },
  {
   "title": "Average User down time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(solana_validators_monitoring_down_time)"
    }
   ]
  },
  {
   "title": "Average cluster vote distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": " slots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validators_monitoring_cluster_avg_vote_distance"
    }
   ]
  },
  {
   "title": "Operators vote distance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "solana_validators_monitoring_vote_distance",
     "legendFormat": "{{ operator }} "
    }
   ]
  },
  {
   "title": "Average User vote distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": " slots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(solana_validators_monitoring_vote_distance)"
    }
   ]
  }
 ]
}