global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'solana-vadidators-monitoring'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - "alerts_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'main'
    static_configs:
      - targets: ['main:3000']
