apiVersion: 1

datasources:

  - name: PostgreSQL
    type: postgres
    typeName: PostgreSQL
    access: proxy
    url: db:5432
    uid: LOn97bynk
    user: solana
    database: solana
    basicAuth: false
    isDefault: true
    jsonData:
      postgresVersion: 1200
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      tlsSkipVerify: true
    secureJsonData:
      password: solana
    readOnly: false

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    editable: true
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar

  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    uid: P7647F508D5F54FCB
    jsonData:
      implementation: 'prometheus'
    editable: false
