name: Linters

on: push

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
